import { useQuery } from "@tanstack/react-query";
import { Link } from "wouter";
import { Printer } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SectionLoader } from "@/components/shared/loading";
import { useEstate } from "@/hooks/useEstate";
import { api } from "@/lib/api";
import { BRAND_NAME, COMPANY_NAME } from "@shared/brand";
import type { EstateAnalytics } from "@shared/types";

// AGM-ready monthly estate report — the summary no estate secretary
// compiles by hand today. Renders from data the analytics endpoint
// already serves, styled for paper: window.print() + @media print rules
// (the print stylesheet lives in index.css under .print-report).
export default function AdminReportPage() {
  const { data: estate } = useEstate();
  const { data: a, isLoading } = useQuery<EstateAnalytics>({
    queryKey: ["analytics"],
    queryFn: () => api.get<EstateAnalytics>("/api/analytics").then((r) => r.data),
    staleTime: 5 * 60 * 1000,
  });

  const now = new Date();
  const monthLabel = now.toLocaleDateString("en-KE", { month: "long", year: "numeric" });
  const thisMonthTotal = a?.payments.monthlyTotals[a.payments.monthlyTotals.length - 1]?.total ?? 0;
  const levyPct = a && a.payments.levyStatus.totalResidents > 0
    ? Math.round((a.payments.levyStatus.paidCount / a.payments.levyStatus.totalResidents) * 100)
    : 0;

  if (isLoading || !a) {
    return (
      <div className="page-wrap"><main className="container-list pt-8"><SectionLoader /></main></div>
    );
  }

  const Stat = ({ label, value }: { label: string; value: string | number }) => (
    <div className="border border-[#D4C9A8] rounded-xl p-3 text-center">
      <p className="font-black text-2xl text-[#1B5E20]">{value}</p>
      <p className="text-[11px] font-semibold text-[#6B5D45] uppercase tracking-wide mt-0.5">{label}</p>
    </div>
  );

  return (
    <div className="min-h-screen bg-white">
      <main className="max-w-3xl mx-auto px-6 py-8 print-report">
        {/* Screen-only toolbar */}
        <div className="flex items-center justify-between mb-6 print:hidden">
          <Link href="/dashboard/admin" className="text-sm text-[#1B5E20] font-semibold">← Back</Link>
          <Button onClick={() => window.print()} className="gap-1.5">
            <Printer className="h-4 w-4" /> Print / Save as PDF
          </Button>
        </div>

        {/* Report header */}
        <header className="border-b-2 border-[#1B5E20] pb-4 mb-6">
          <p className="text-xs font-bold uppercase tracking-[0.2em] text-[#6B5D45]">Monthly Estate Report</p>
          <h1 className="font-black text-3xl text-[#212121] mt-1">{estate?.name ?? "Estate"}</h1>
          <p className="text-sm text-[#6B5D45] mt-0.5">
            {monthLabel} · Prepared {now.toLocaleDateString("en-KE", { day: "numeric", month: "long", year: "numeric" })} · Generated by {BRAND_NAME}
          </p>
        </header>

        {/* Finances */}
        <section className="mb-6">
          <h2 className="font-bold text-base text-[#212121] mb-3">1. Finances</h2>
          <div className="grid grid-cols-3 gap-3 mb-3">
            <Stat label="Collected this month" value={`KES ${Number(thisMonthTotal).toLocaleString("en-KE")}`} />
            <Stat label="Levy compliance" value={`${levyPct}%`} />
            <Stat label="Residents paid" value={`${a.payments.levyStatus.paidCount}/${a.payments.levyStatus.totalResidents}`} />
          </div>
          {a.payments.levyStatus.unpaidResidents.length > 0 && (
            <p className="text-xs text-[#6B5D45]">
              Outstanding: {a.payments.levyStatus.unpaidResidents.map((r) => `${r.name}${r.unitNumber ? ` (${r.unitNumber})` : ""}`).join(", ")}
            </p>
          )}
        </section>

        {/* Maintenance */}
        <section className="mb-6">
          <h2 className="font-bold text-base text-[#212121] mb-3">2. Maintenance</h2>
          <div className="grid grid-cols-3 gap-3 mb-3">
            <Stat label="Open" value={a.maintenance.open} />
            <Stat label="In progress" value={a.maintenance.inProgress} />
            <Stat label="Resolved" value={a.maintenance.resolved} />
          </div>
          {Object.keys(a.maintenance.byCategory).length > 0 && (
            <p className="text-xs text-[#6B5D45]">
              By category: {Object.entries(a.maintenance.byCategory).map(([c, n]) => `${c} ${n}`).join(" · ")}
            </p>
          )}
        </section>

        {/* Security & gate */}
        <section className="mb-6">
          <h2 className="font-bold text-base text-[#212121] mb-3">3. Security &amp; Gate</h2>
          <div className="grid grid-cols-3 gap-3">
            <Stat label="Visitors this month" value={a.visitors.thisMonth} />
            <Stat label="Parcels this month" value={a.parcels.thisMonth} />
            <Stat label="Alerts this month" value={a.emergency.thisMonth} />
          </div>
        </section>

        {/* Community */}
        <section className="mb-8">
          <h2 className="font-bold text-base text-[#212121] mb-3">4. Community</h2>
          <div className="grid grid-cols-3 gap-3">
            <Stat label="Registered residents" value={a.residents.total} />
            <Stat label="Total collected (all time)" value={`KES ${Number(a.payments.totalCollected).toLocaleString("en-KE")}`} />
            <Stat label="Parcels at gate now" value={a.parcels.atGate} />
          </div>
        </section>

        <footer className="border-t border-[#D4C9A8] pt-3">
          <p className="text-[10px] text-[#6B5D45]">
            Generated automatically from live estate records by {BRAND_NAME} ({COMPANY_NAME}).
            Figures reflect the state at time of generation.
          </p>
        </footer>
      </main>
    </div>
  );
}
